### ISSUE TITLE
Ideal way to copy a filearray

### ISSUE THREAD

**Issue by talegari** [dipterix/filearray#8]
Hi @dipterix,

Thanks for this great package!
What is the ideal way to create a copy of filearray? (not reference, actual copy on disk)

Right now, this works:

```r
fs::dir_copy(fa_obj$.filebase, "newfile")
filearray_load("newfile")
```

Would it be better to provide a copy method to filearray class?

**Comment by dipterix** [comment]
You are doing great. 

Copying the folder will be sufficient & necessary. Basically `filearray` stores data into partitions with one or multiple header files (usually just one), in the same **portable** folder. This structure will unlikely to change in the future.

I'm a little bit hesitated to add native support to copy the arrays. The original purpose for this package is that I can create a filearray object and access (readonly) from multiple R programs for parallel computing, rather than copying multiple GB of files/data around. Is there any reason for you to do this?

**Comment by dipterix** [comment]
Juse realized `filearray_bind(x, filebase = "new/path", symlink = FALSE)` should do the work
